# Site Settings
title: "INSU's Blog"
description: "데이터 사이언스와 머신러닝에 관한 블로그"
author: "INSU"
url: "https://insu97.github.io"

paginate: 10
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

timezone: Asia/Seoul

include:
  - .well-known

# 목차 설정 [ ## ~ ####]
toc:
  min_level: 2
  max_level: 3

# Search JSON 설정
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# search.json이 정상적으로 생성되도록 layout 설정
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post

# site.baseurl 예: /myblog (Github Pages라면)
baseurl: ''
